# Generated by Django 6.0.4 on 2026-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='last_webhook_event',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='plan_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
