# Generated by Django 6.0.4 on 2026-04-07 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entitlement_last_webhook_event_entitlement_plan_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('timer_state', models.JSONField(blank=True, default=dict)),
                ('annotation_state', models.JSONField(blank=True, default=dict)),
                ('activity_state', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='core.readingsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
