# Generated by Django 6.0.4 on 2026-04-08 20:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_readingreminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("image_url", models.URLField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.book",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
                "unique_together": {("book", "page_number")},
            },
        ),
    ]
