# Generated by Django 6.0.4 on 2026-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_asset_type_s3_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Bailey & Beau', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('default_from_email', models.CharField(blank=True, max_length=254)),
                ('public_base_url', models.URLField(blank=True)),
                ('default_session_duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('session_warning_one_minutes', models.PositiveSmallIntegerField(default=5)),
                ('session_warning_two_minutes', models.PositiveSmallIntegerField(default=2)),
                ('invite_link_type_label', models.CharField(blank=True, default='Single use', max_length=80)),
                ('stripe_secret_key', models.TextField(blank=True)),
                ('stripe_webhook_secret', models.TextField(blank=True)),
                ('livekit_api_key', models.CharField(blank=True, max_length=255)),
                ('livekit_api_secret', models.TextField(blank=True)),
                ('livekit_url', models.URLField(blank=True)),
                ('storage_plan_total_gb', models.PositiveIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal settings',
                'verbose_name_plural': 'Portal settings',
            },
        ),
    ]
