# Generated by Django 6.0.4 on 2026-07-20 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_sessioninvite_increase_max_uses"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingsession",
            name="completed_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_in_sessions",
                to="core.activityconfig",
            ),
        ),
        migrations.AddField(
            model_name="readingsession",
            name="completed_activity_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
