# Generated by Django 6.0.4 on 2026-07-27 19:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_readingsession_completed_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTheme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "backdrop_kind",
                    models.CharField(
                        choices=[
                            ("color", "Solid colour"),
                            ("gradient", "Gradient"),
                            ("image", "Image"),
                            ("video", "Video"),
                        ],
                        default="gradient",
                        max_length=10,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex colour such as #3D3B62.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "bg_color_2",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex colour such as #3D3B62.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                            )
                        ],
                    ),
                ),
                ("gradient_angle", models.PositiveSmallIntegerField(default=170)),
                ("bg_image", models.ImageField(blank=True, upload_to="themes/bg/")),
                ("bg_video", models.FileField(blank=True, upload_to="themes/video/")),
                (
                    "bg_video_poster",
                    models.ImageField(blank=True, upload_to="themes/poster/"),
                ),
                (
                    "accent",
                    models.CharField(
                        default="#3D3B62",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex colour such as #3D3B62.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "ink",
                    models.CharField(
                        default="#23324A",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex colour such as #3D3B62.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "chrome_mode",
                    models.CharField(
                        choices=[("light", "Light chrome"), ("dark", "Dark chrome")],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "book_shadow",
                    models.CharField(
                        choices=[("none", "None"), ("soft", "Soft"), ("deep", "Deep")],
                        default="soft",
                        max_length=10,
                    ),
                ),
                ("tilt_degrees", models.SmallIntegerField(default=-2)),
                (
                    "ambient_audio",
                    models.FileField(blank=True, upload_to="themes/audio/"),
                ),
                ("ambient_volume", models.PositiveSmallIntegerField(default=20)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="core.book",
                    ),
                ),
            ],
            options={
                "ordering": ["book__title"],
            },
        ),
    ]
