# Generated by Django 6.0.4 on 2026-08-01 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_booktheme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.URLField(blank=True)),
                ("age_band", models.CharField(blank=True, max_length=10)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("accent", models.CharField(default="#3d3b62", max_length=9)),
                ("cover_image", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="activityconfig",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_configs",
                to="core.book",
            ),
        ),
        migrations.AlterField(
            model_name="readingsession",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="core.book",
            ),
        ),
        migrations.AddField(
            model_name="activityconfig",
            name="activity_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_configs",
                to="core.activitygroup",
            ),
        ),
        migrations.AddField(
            model_name="readingsession",
            name="activity_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="core.activitygroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("activity_group__isnull", True), ("book__isnull", False)),
                    models.Q(("activity_group__isnull", False), ("book__isnull", True)),
                    _connector="OR",
                ),
                name="activityconfig_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("activity_group__isnull", True), ("book__isnull", False)),
                    models.Q(("activity_group__isnull", False), ("book__isnull", True)),
                    _connector="OR",
                ),
                name="readingsession_exactly_one_target",
            ),
        ),
        migrations.AddField(
            model_name="activitygroup",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_groups",
                to="core.theme",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="theme_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="core.theme",
            ),
        ),
    ]
